name: Publish lexaddon.py on Tag Creation

on:
  push:
    tags:
      - 'v*'  # Trigger on any tag creation starting with 'v'

jobs:
  publish-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload lexaddon.py
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        asset_path: ./lexaddon.py
        asset_name: lexaddon.py
        asset_content_type: text/plain
